### ISSUE TITLE
"Next" button not working

### ISSUE THREAD

**Issue by parkeraa** [BYUCamachoLab/Photonics-Bootcamp#14]
In the [online version](https://byucamacholab.github.io/Photonics-Bootcamp/index.html) of the book the "Next" button and the link to the next page don't work, they don't do anything when clicked.

**Comment by sequoiap** [comment]
It is very much due to the ChatTutor widget—seems to control that area of the webpage even when it isn't open?

**Comment by kerfun** [comment]
This has now been resolved.
